#! python3

import sys

from apollon.hmm_factory import build
from apollon.hmm_factory import utilities


def main():
    """Insert doc string.
    """    
    opts, args = utilities.__parse_cml()
    path = utilities.__validate_input_path(args[0])
    
    for afp in path:
        build.PoissonHMM(afp)


if __name__ == "__main__":
    sys.exit(main())
