#!/usr/bin/env python3

import numpy as np
from optparse import OptionParser
from pathlib import Path
import sys

from apollon.hmm import graph
from apollon.io import load


def main(argv=None):
    """Draw the tpm of a HMM as directed graph.
    """
    if argv is None:
        argv = sys.argv

    opts, args = _parse_cmd(argv)
    in_file = Path(args[0])

    tpm = load(in_file)
    fig, ax, img = graph.draw_matrix(tpm.round(3).astype(float))
    graph.save_hmmfig(fig, in_file.stem+'_matrix.jpg')
    #fig, ax, img = graph.draw_network(tpm.round(3).astype(float))
    #graph.save_hmmfig(fig, in_file.stem+'_network.jpg')

    return 0


def _parse_cmd(argv):
    usage = 'Usage: %prog [OPTIONS] path_to_hmm'
    parser = OptionParser(usage=usage)

    parser.add_option('-v', '--verbose', action='store_true',
                      dest='verbose', default=False,
                      help='Be a little more verbose.')

    opts, args = parser.parse_args()

    if len(args) != 1:
        print('Wrong number of arguments.')
        parser.print_help(sys.stderr)
        sys.exit(1)

    return opts, args


if __name__ == "__main__":
    sys.exit(main())



