name: tests
on: [push]
jobs:
  run-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python $${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: poetry install --with=development
      - name: Testing ...
        run: poetry run -- python -m unittest
